export const photos = {
  teamMeeting: "/photos/team-meeting.jpg",
  agencyWork: "/photos/agency-work.jpg",
  collaboration: "/photos/collaboration.jpg",
  workshop: "/photos/workshop.jpg",
  metaAds: "/photos/facebook-ads.png",
  googleAds: "/photos/google-ads.jpg",
  amazonAds: "/photos/amazon-ads.jpg",
  seo: "/photos/seo.jpg",
  webDev: "/photos/web-dev.jpg",
  email: "/photos/email.jpg",
  shopify: "/photos/shopify.jpg",
  instagram: "/photos/instagram.jpg",
  content: "/photos/content.jpg",
  analytics: "/photos/analytics.jpg",
  meeting: "/photos/meeting.jpg",
};
